### PR TITLE
Fixed bug with placeholder

### PR DESCRIPTION
**Pull request by nikelborm**
Bug:

When placeholder is provided and there is no value, placeholder renders fine in the textarea, but it does not render in the preview.

### CODE REVIEW

**Comment by jaywcjlove** [comment]
image

@nikelborm This is a function that comes with the html `<textarea>` tag, and there will be no bugs.
There may be style conflicts.

I tested and there are no bugs

**Comment by nikelborm** [comment]
> image
> 
> @nikelborm This is a function that comes with the html `<textarea>` tag, and there will be no bugs. There may be style conflicts.
> 
> I tested and there are no bugs

Did you tested it in firefox? because for me in firefox this does not work properly

preview overlaps textarea and in the end I don't see the placeholder

**Comment by nikelborm** [comment]
Ahah, I found where was the problem

I didn`t see the placeholder because my parent component is `display:flex` and it squeeze code editor

Screenshot_20220426_105200

Screenshot_20220426_105326


But when I disabled flex it works fine

What should we do with this?
In this flex case I think this manual setting of placeholder will be still usefull

**Comment by nikelborm** [comment]
Check my last commit with https://github.com/uiwjs/react-textarea-code-editor/pull/114/commits/49e33106d568f79189a32436c38fcf5c6aa57fd2#diff-f87270b29523717f9e20dac3310b24d5bf58c893da983f8df0745ae3179c45a0R79
 
If I remove this placholder thing from here https://github.com/uiwjs/react-textarea-code-editor/pull/114/commits/d305a988701ac425fe39b04d78e850cb365a3b92#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405R65

My test case will look like this
Screenshot_20220426_111619

**Comment by nikelborm** [comment]
With fix enabled it will look like this

Screenshot_20220426_111826

**Pull request merged**
